# Generated by Django 2.0 on 2020-04-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_customer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sub',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
